config/routes.rb
Rails.application.routes.draw do

get    "/albums/index",     to: "albums#index",   as: :albums_index

post   "/albums/:id",       to: "albums#upvote",  as: :album

post   "/albums",           to: "albums#create",  as: :albums
get    "/albums/new",       to: "albums#new",     as: :new_album

get    "/albums/:id",       to: "albums#show"

put    "/albums/:id",       to: "albums#update"
patch  "/albums/:id",       to: "albums#update"

get    "/albums/:id/edit",  to: "albums#edit",    as: :edit_album
post   "/albums/:id/edit",  to: "albums#edit"

delete "/albums/:id",       to: "albums#destroy"

get    "/books/index",     to: "books#index",   as: :books_index

post   "/books/:id",       to: "books#upvote",  as: :book

post   "/books",           to: "books#create",  as: :books
get    "/books/new",       to: "books#new",     as: :new_book

get    "/books/:id",       to: "books#show"

put    "/books/:id",       to: "books#update"
patch  "/books/:id",       to: "books#update"

get    "/books/:id/edit",  to: "books#edit",    as: :edit_book
post   "/books/:id/edit",  to: "books#edit"

delete "/books/:id",       to: "books#destroy"

get    "/movies/index",     to: "movies#index",   as: :movies_index

post   "/movies/:id",       to: "movies#upvote",  as: :movie

post   "/movies",           to: "movies#create",  as: :movies
get    "/movies/new",       to: "movies#new",     as: :new_movie

get    "/movies/:id",       to: "movies#show"

put    "/movies/:id",       to: "movies#update"
patch  "/movies/:id",       to: "movies#update"

get    "/movies/:id/edit",  to: "movies#edit",    as: :edit_movie
post   "/movies/:id/edit",  to: "movies#edit"

delete "/movies/:id",       to: "movies#destroy"

root to: "media_ranker#index"

end

app/models/album.rb
class Album < ActiveRecord::Base
  belongs_to :media_ranker
  validates :creator, presence: true
  validates :name, presence: true
  validates :description, presence: true

end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :media_ranker
  validates :creator, presence: true
  validates :name, presence: true
  validates :description, presence: true


end

app/models/media_ranker.rb
class MediaRanker < ActiveRecord::Base
  has_many :books
  has_many :movies
  has_many :albums
end

app/models/movie.rb
class Movie < ActiveRecord::Base
  belongs_to :media_ranker
  validates :creator, presence: true
  validates :name, presence: true
  validates :description, presence: true

end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController


  def index
    @albums = Album.all
  end

  def new
    @album = Album.new
  end

  def create
    @album = Album.new(album_params)
    if @album.save
      redirect_to albums_index_path
    else
      render :new
    end
  end

  def show
    @album = Album.find(params[:id])
  end

  def edit
    @album = Album.find(params[:id])
  end

  def update
    @album = Album.find(params[:id])
    if @album.update(album_params)
      redirect_to albums_index_path
    else
      render :edit
    end

  end

  def destroy
    @album = Album.find(params[:id])
    if @Album.destroy
      redirect_to albums_index_path
    end
  end


  def upvote
    @album = Album.find(params[:id])
    if @album.votes == nil
      @album.votes = 1
    else
      @album.votes += 1
    end
    @album.save
    redirect_to request.referer
  end


  private


  def album_params
    params.require(:album).permit(:name, :creator, :description)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
   protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController


  def index
    @books = Book.all
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to books_index_path
    else
      render :new
    end
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to books_index_path
    else
      render :edit
    end

  end

  def destroy
    @book = Book.find(params[:id])
    if @book.destroy
      redirect_to books_index_path
    end
  end


  def upvote
    @book = Book.find(params[:id])
    if @book.votes == nil
      @book.votes = 1
    else
      @book.votes += 1
    end
    @book.save
    redirect_to request.referer
  end


  private


  def book_params
    params.require(:book).permit(:name, :creator, :description)
  end

end

app/controllers/media_ranker_controller.rb
class MediaRankerController < ApplicationController

  def index
    @movies = Movie.all
    @albums = Album.all
    @books  = Book.all
  end

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController


  def index
    @movies = Movie.all
  end

  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.new(movie_params)
    if @movie.save
      redirect_to movies_index_path
    else
      render :new
    end
  end

  def show
    @movie = Movie.find(params[:id])
  end

  def edit
    @movie = Movie.find(params[:id])
  end

  def update
    @movie = Movie.find(params[:id])
    if @movie.update(movie_params)
      redirect_to movies_index_path
    else
      render :edit
    end

  end


  def destroy
    @movie = Movie.find(params[:id])
    if @movie.destroy
      redirect_to movies_index_path
    end
  end


  def upvote
    @movie = Movie.find(params[:id])
    if @movie.votes == nil
      @movie.votes = 1
    else
      @movie.votes += 1
    end
    @movie.save
    redirect_to request.referer
  end


  private


  def movie_params
    params.require(:movie).permit(:name, :creator, :description)
  end

end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/media_ranker_helper.rb
module MediaRankerHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/albums/edit.html.erb
<h1>Edit <%= @album.name %></h1>


<%= bootstrap_form_for @album do |f| %>
  <%= f.text_field :name, label: "Title" %>

  <%= f.text_area :creator, label: "Artist" %>

  <%= f.text_area :description, label: "Description" %>

  <%= f.submit %>
<% end %>

app/views/albums/index.html.erb
<h1>Albums</h1>

<table class="table table-hover">
  <tr>
    <th>Rank</th>
    <th>Album</th>
    <th>Author</th>
    <th>Description</th>
    <th>Upvote</th>



  </tr>

  <% @albums.each do |album|%>
  <tr>

    <td><%= album.votes %></td>
    <td><%= link_to(album.name, album_path(album.id))  %></td>
    <td><%= album.creator %></td>
    <td><%= album.description %></td>
    <td><%= button_to "upvote", album_path(album.id), {class: 'btn btn-info'} %></td>

  </tr>

  <% end %>

</table>

<%= link_to "New Album", new_album_path, class: 'btn btn-success' %>

app/views/albums/new.html.erb
<h1>Albums</h1>

<%= bootstrap_form_for @album do |f| %>
  <%= f.text_field :name, label: "Title" %>

  <%= f.text_area :creator, label: "Artist" %>

  <%= f.text_area :description, label: "Description" %>

  <%= f.submit %>

<% end %>

app/views/albums/show.html.erb
<h1><%= @album.name %></h1>
<h4> <%= @album.creator %> </h4>

<p><%= @album.description %></p>

<h6> <%= @album.votes %></h6>
<div class="buttons-above"><%= button_to "upvote", album_path(@album.id), {class: 'btn btn-info'} %></div>

<div class="buttons-show">
  <%= button_to "Edit", "/albums/#{@album.id}/edit", {class: 'btn btn-info'} %>
  <%= button_to "Delete", album_path, method: :delete, class: 'btn btn-danger' %>
  <%= link_to "All Albums", albums_index_path, class: 'btn btn-default' %>
  <%= link_to "View All Media", root_path, class: 'btn btn-default' %>
</div>

app/views/books/edit.html.erb
<h1>Edit <%= @book.name %></h1>


<%= bootstrap_form_for @book do |f| %>
  <%= f.text_field :name, label: "Title" %>

  <%= f.text_area :creator, label: "Author" %>

  <%= f.text_area :description, label: "Description" %>

  <%= f.submit %>
<% end %>

app/views/books/index.html.erb
<h1>Books</h1>

<table class="table table-hover">
  <tr>
    <th>Rank</th>
    <th>Book</th>
    <th>Author</th>
    <th>Description</th>
    <th>Upvote</th>



  </tr>

  <% @books.each do |book|%>
  <tr>

    <td><%= book.votes %></td>
    <td><%= link_to(book.name, book_path(book.id))  %></td>
    <td><%= book.creator %></td>
    <td><%= book.description %></td>
    <td><%= button_to "upvote", book_path(book.id), {class: 'btn btn-info'} %></td>

  </tr>

  <% end %>

</table>

<%= link_to "New Book", new_book_path, class: 'btn btn-success' %>

app/views/books/new.html.erb
<h1>Books</h1>

<%= bootstrap_form_for @book do |f| %>
  <%= f.text_field :name, label: "Title" %>

  <%= f.text_area :creator, label: "Author" %>

  <%= f.text_area :description, label: "Description" %>

  <%= f.submit %>
<% end %>

app/views/books/show.html.erb
<h1><%= @book.name %></h1>
<h4> <%= @book.creator %> </h4>

<p><%= @book.description %></p>

<h6> <%= @book.votes %></h6>
<div class="buttons-above"><%= button_to "upvote", book_path(@book.id), {class: 'btn btn-info'} %></div>

<div class="buttons-show">
  <%= button_to "Edit", "/books/#{@book.id}/edit", {class: 'btn btn-info'} %>
  <%= button_to "Delete", book_path, method: :delete, class: 'btn btn-danger' %>
  <%= link_to "All Books", books_index_path, class: 'btn btn-default' %>
  <%= link_to "View All Media", root_path, class: 'btn btn-default' %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mediaranker</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
<div class="header">
  <h1>
    <%= image_tag "Fist.png", size: "100" %>
    <%= link_to "RANKER", root_path %>
  </h1>
</div>

<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <div class="col">
        <%= yield %>
      </div>
    </div>
  </div>
</div>





</body>
</html>

app/views/media_ranker/index.html.erb
<div class="col1 col-sm-4">
  <h2 class="test"><%= link_to "Movies", movies_index_path %></h2>
    <% @movies.each do |movie|%>
       <h3><%= link_to(movie.name, movie_path(movie.id))  %>
          <%= movie.votes %></h3>
    <% end %>
    <%= link_to("See all movies", movies_index_path) %>

</div>

<div class="col2 col-sm-4">
  <h2 class="test"><%= link_to "Albums", albums_index_path %></h2>
    <% @albums.each do |a|%>
       <h3><%= link_to(a.name, album_path(a.id))  %>
          <%= a.votes %></h3>
    <% end %>
    <%= link_to("See all albums", albums_index_path) %>
</div>

<div class="col3 col-sm-4">
  <h2 class="test"><%= link_to "Books", books_index_path %></h2>
  <% @books.each do |b|%>
     <h3><%= link_to(b.name, book_path(b.id))  %>
        <%= b.votes %></h3>
  <% end %>
  <%= link_to("See all books", books_index_path) %>
</div>

app/views/movies/edit.html.erb
<h1>Edit <%= @movie.name %></h1>





<%= bootstrap_form_for @movie do |f| %>
  <%= f.text_field :name, label: "Title" %>

  <%= f.text_area :creator, label: "Director" %>

  <%= f.text_area :description, label: "Description" %>

  <%= f.submit %>
<% end %>

app/views/movies/index.html.erb
<h1>Movies</h1>

<table class="table table-hover">
  <tr>
    <th>Rank</th>
    <th>Movie</th>
    <th>Director</th>
    <th>Description</th>
    <th>Upvote</th>



  </tr>

  <% @movies.each do |movie|%>
  <tr>

    <td><%= movie.votes %></td>
    <td><%= link_to(movie.name, movie_path(movie.id))  %></td>
    <td><%= movie.creator %></td>
    <td><%= movie.description %></td>
    <td><%= button_to "upvote", movie_path(movie.id), {class: 'btn btn-info'} %></td>

  </tr>

  <% end %>

</table>

<%= link_to "New Movie", new_movie_path, class: 'btn btn-success' %>

app/views/movies/new.html.erb
<h1>Movies</h1>

<%= bootstrap_form_for @movie do |f| %>
  <%= f.text_field :name, label: "Title" %>

  <%= f.text_area :creator, label: "Director" %>

  <%= f.text_area :description, label: "Description" %>

  <%= f.submit %>

<% end %>

app/views/movies/show.html.erb
<h1><%= @movie.name %></h1>
<h4> <%= @movie.creator %> </h4>

<p><%= @movie.description %></p>

<h6> <%= @movie.votes %></h6>
<div class="buttons-above"><%= button_to "upvote", movie_path(@movie.id), {class: 'btn btn-info'} %></div>

<div class="buttons-show">
  <%= button_to "Edit #{@movie.name}", "/movies/#{@movie.id}/edit", class: 'btn btn-info' %>
  <%= button_to "Delete", movie_path, method: :delete, class: 'btn btn-danger' %>
  <%= link_to "All Movies", movies_index_path, class: 'btn btn-default' %>
  <%= link_to "View All Media", root_path, class: 'btn btn-default' %>

</div>